### ISSUE TITLE
Glitch in progress bar and visualiser

### ISSUE THREAD

**Issue by isham-mohamed** [JagarYousef/ChatVoicePlayer#9]
there is a glitch in the seek bar when played multiple times

**Comment by JagarYousef** [comment]
Does this happen when you use the waveform or without it? Attaching more details or a short video will be a great help to understand the situation

**Comment by isham-mohamed** [comment]
in both seek bar and waveform

**Comment by cnnax** [comment]
I also have the same issue , app totally crashes when i click on seekbar

**Comment by JagarYousef** [comment]
@cnnax can I attach your logcat when the crush happens?

**Comment by cnnax** [comment]
> @cnnax can you attach your logcat when it crashes?

Sure , 


`D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.codenear.chatfinderv4, PID: 14502
    java.lang.ClassCastException: android.view.ContextThemeWrapper cannot be cast to android.app.Activity
        at me.jagar.chatvoiceplayerlibrary.VoicePlayerView.update(VoicePlayerView.java:315)
        at me.jagar.chatvoiceplayerlibrary.VoicePlayerView.access$800(VoicePlayerView.java:35)
        at me.jagar.chatvoiceplayerlibrary.VoicePlayerView$4.onProgressChanged(VoicePlayerView.java:241)
        at android.widget.SeekBar.onProgressRefresh(SeekBar.java:98)
        at android.widget.ProgressBar.doRefreshProgress(ProgressBar.java:1553)
        at android.widget.ProgressBar.refreshProgress(ProgressBar.java:1609)
        at android.widget.ProgressBar.setProgressInternal(ProgressBar.java:1675)
        at android.widget.AbsSeekBar.trackTouchEvent(AbsSeekBar.java:977)
        at android.widget.AbsSeekBar.startDrag(AbsSeekBar.java:933)
        at android.widget.AbsSeekBar.onTouchEvent(AbsSeekBar.java:880)
        at android.view.View.dispatchTouchEvent(View.java:13598)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3078)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2709)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3078)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2709)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3078)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2709)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3078)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2709)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3078)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2709)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3078)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2709)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3078)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2709)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3078)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2709)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3078)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2709)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3078)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2709)
        at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:529)
        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1866)
        at android.app.Dialog.dispatchTouchEvent(Dialog.java:873)
        at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:479)
        at android.view.View.dispatchPointerEvent(View.java:13857)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6046)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5804)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5255)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5315)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5274)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5439)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5282)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5496)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5255)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5315)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5274)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5282)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5255)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8130)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8099)
E/AndroidRuntime:     at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8052)
        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:8260)
        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:189)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:336)
        at android.os.Looper.loop(Looper.java:184)
        at android.app.ActivityThread.main(ActivityThread.java:7840)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:985)`

**Comment by JagarYousef** [comment]
This should be fixed in the last update,
If it is still valid please feel free to reopen or open a new issue
